/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from 'ethers';
import type { Provider } from '@ethersproject/providers';
import type { PERMIT2, PERMIT2Interface } from '../PERMIT2';

const _abi = [
  {
    inputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
    ],
    name: 'allowance',
    outputs: [
      {
        internalType: 'uint160',
        name: 'amount',
        type: 'uint160',
      },
      {
        internalType: 'uint48',
        name: 'expiration',
        type: 'uint48',
      },
      {
        internalType: 'uint48',
        name: 'nonce',
        type: 'uint48',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
] as const;

export class PERMIT2__factory {
  static readonly abi = _abi;
  static createInterface(): PERMIT2Interface {
    return new utils.Interface(_abi) as PERMIT2Interface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): PERMIT2 {
    return new Contract(address, _abi, signerOrProvider) as PERMIT2;
  }
}
